/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AtividadeLPII;
import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author anderson
 */
public final class AdmProduto extends javax.swing.JFrame {

    /**
     * Creates new form atividades
     */
   // Class.forName("com.mysql.cj.jdbc.Driver");  
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
            public AdmProduto() {
        initComponents();
        showTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpProduto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NomeProduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Categoria = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        preco = new javax.swing.JTextField();
        codigo = new javax.swing.JTextField();
        cadastrar = new javax.swing.JButton();
        atualizar = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        novo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        descricao = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        quantidade = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProduto = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Produtos");
        setName("jfProduto"); // NOI18N

        jpProduto.setBackground(new java.awt.Color(198, 231, 248));

        jLabel1.setText("Cod.");

        jLabel2.setText("Nome Produto :");

        jLabel3.setText("Categoria :");

        jLabel4.setText("Preço :");

        cadastrar.setText("Cadastrar");
        cadastrar.setMaximumSize(null);
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        atualizar.setText("Atualizar");
        atualizar.setMaximumSize(null);
        atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarActionPerformed(evt);
            }
        });

        excluir.setText("Excluir");
        excluir.setMaximumSize(null);
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });

        novo.setText("Voltar");
        novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoActionPerformed(evt);
            }
        });

        jLabel5.setText("Descrição:");

        jLabel6.setText("Quantidade:");

        tabelaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tabelaProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaProduto);

        javax.swing.GroupLayout jpProdutoLayout = new javax.swing.GroupLayout(jpProduto);
        jpProduto.setLayout(jpProdutoLayout);
        jpProdutoLayout.setHorizontalGroup(
            jpProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpProdutoLayout.createSequentialGroup()
                .addGroup(jpProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpProdutoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jpProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpProdutoLayout.createSequentialGroup()
                                .addGroup(jpProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jpProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(quantidade)
                                    .addComponent(descricao)
                                    .addComponent(preco)
                                    .addComponent(Categoria)
                                    .addComponent(NomeProduto)
                                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpProdutoLayout.createSequentialGroup()
                                .addComponent(atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(novo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpProdutoLayout.setVerticalGroup(
            jpProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpProdutoLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(42, 42, 42))
            .addGroup(jpProdutoLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(novo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jpProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jpProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jpProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jpProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jpProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(23, 23, 23)
                .addGroup(jpProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(excluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addComponent(jpProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jpProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(619, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarActionPerformed
        // TODO add your handling code here:
        try
        {
            String Sql=" update produto set prod_categoria=?,nome=?,prod_descricao=?,prod_preco=?,prod_quantidade=? where prod_id=?";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/acai","root","Pro@1974");  
            pst = con.prepareStatement(Sql);
            pst.setString(6,codigo.getText());
            pst.setString(1,Categoria.getText());
            pst.setString(2,NomeProduto.getText());
            pst.setString(3,descricao.getText());
            pst.setString(4,preco.getText());
            pst.setString(5,quantidade.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Cadastro Realizado com Sucesso!","Cadastro", HEIGHT);
            
        
        }catch (HeadlessException ex){ 
    JOptionPane.showMessageDialog(rootPane, ex,"Erro", HEIGHT);
    }   catch (SQLException ex) {   
        JOptionPane.showMessageDialog(rootPane, ex,"Erro", HEIGHT);
        }   
       showTableData(); 
       limpatxt();
    }//GEN-LAST:event_atualizarActionPerformed

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        // TODO add your handling code here:
        try
        {
            String Sql=" insert into produto values (?,?,?,?,?,?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/acai","root","Pro@1974");  
            pst = con.prepareStatement(Sql);
            pst.setString(1,codigo.getText());
            pst.setString(2,Categoria.getText());
            pst.setString(3,NomeProduto.getText());
            pst.setString(4,descricao.getText());
            pst.setString(5,preco.getText());
            pst.setString(6,quantidade.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Cadastro Realizado com Sucesso!","Cadastro", HEIGHT);
            
        
        }catch (HeadlessException ex){ 
    JOptionPane.showMessageDialog(rootPane, ex,"Erro", HEIGHT);
    }   catch (SQLException ex) {   
        JOptionPane.showMessageDialog(rootPane, ex,"Erro", HEIGHT);
        }   
        showTableData();
        limpatxt();
    }//GEN-LAST:event_cadastrarActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        // TODO add your handling code here:
        try
        {
            String Sql=" delete from produto  where prod_id=?";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/acai","root","Pro@1974");  
            pst = con.prepareStatement(Sql);
            pst.setString(1,codigo.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Exclusão realizada com Sucesso!","Cadastro", HEIGHT);
            
        
        }catch (HeadlessException ex){ 
    JOptionPane.showMessageDialog(rootPane, ex,"Erro", HEIGHT);
    }   catch (SQLException ex) {   
        JOptionPane.showMessageDialog(rootPane, ex,"Erro", HEIGHT);
        }   
        showTableData();
        limpatxt();
    }//GEN-LAST:event_excluirActionPerformed

    private void tabelaProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProdutoMouseClicked
        // TODO add your handling code here:
        // get data of the first shell of a JTable row
    int row = tabelaProduto.getSelectedRow();
        codigo.setText(tabelaProduto.getModel().getValueAt(row, 0).toString());
        Categoria.setText(tabelaProduto.getModel().getValueAt(row, 1).toString());
        NomeProduto.setText(tabelaProduto.getModel().getValueAt(row, 2).toString());
        descricao.setText(tabelaProduto.getModel().getValueAt(row, 3).toString());
        preco.setText(tabelaProduto.getModel().getValueAt(row, 4).toString());
        quantidade.setText(tabelaProduto.getModel().getValueAt(row, 5).toString());
        
    }//GEN-LAST:event_tabelaProdutoMouseClicked

    private void novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoActionPerformed
        // TODO add your handling code here:
        action ps = new action();
        this.setVisible(false);
        ps.setVisible(true);
    }//GEN-LAST:event_novoActionPerformed

    public void showTableData()
    {
     try
        {
            String Sql=" select * from produto";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/acai","root","Pro@1974");  
            pst = con.prepareStatement(Sql);
            rs = pst.executeQuery();
            tabelaProduto.setModel(DbUtils.resultSetToTableModel(rs));
        }
    catch (HeadlessException ex){ 
    JOptionPane.showMessageDialog(rootPane, ex,"Erro", HEIGHT);
    }   catch (SQLException ex) {   
        JOptionPane.showMessageDialog(rootPane, ex,"Erro", HEIGHT);
        }   
    }
    public void showtableuser()
    {
    try
        {
            String Sql=" select * from funcionarios";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/acai","root","Pro@1974");  
            pst = con.prepareStatement(Sql);
            rs = pst.executeQuery();
            tabelaProduto.setModel(DbUtils.resultSetToTableModel(rs));
        }
    catch (HeadlessException ex){ 
    JOptionPane.showMessageDialog(rootPane, ex,"Erro", HEIGHT);
    }   catch (SQLException ex) {   
        JOptionPane.showMessageDialog(rootPane, ex,"Erro", HEIGHT);
        }   
    
    }
    public void limpatxt(){
    codigo.setText("");
    NomeProduto.setText("");
    Categoria.setText("");
    quantidade.setText("");
    preco.setText("");
    descricao.setText("");
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdmProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdmProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdmProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdmProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AdmProduto().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JTextField Categoria;
    javax.swing.JTextField NomeProduto;
    javax.swing.JButton atualizar;
    javax.swing.JButton cadastrar;
    javax.swing.JTextField codigo;
    javax.swing.JTextField descricao;
    javax.swing.JButton excluir;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabel4;
    javax.swing.JLabel jLabel5;
    javax.swing.JLabel jLabel6;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JPanel jpProduto;
    javax.swing.JButton novo;
    javax.swing.JTextField preco;
    javax.swing.JTextField quantidade;
    javax.swing.JTable tabelaProduto;
    // End of variables declaration//GEN-END:variables
}
