/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AtividadeLPII;
import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author anderson
 */
public final class AdmUser extends javax.swing.JFrame {

    /**
     * Creates new form atividades
     */
   // Class.forName("com.mysql.cj.jdbc.Driver");  
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
            public AdmUser() {
        initComponents();
        showTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpProduto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NomeFuncionario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Usuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Senha = new javax.swing.JTextField();
        cpf = new javax.swing.JTextField();
        cadastrar = new javax.swing.JButton();
        atualizar = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        novo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProduto = new javax.swing.JTable();
        confimSenha = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Produtos");
        setName("jfProduto"); // NOI18N

        jpProduto.setBackground(new java.awt.Color(198, 231, 248));

        jLabel1.setText("CPF:.");

        jLabel2.setText("Nome Funcionarios:");

        jLabel3.setText("Usuario :");

        jLabel4.setText("Senha :");

        Senha.setToolTipText("senha");

        cadastrar.setText("Cadastrar");
        cadastrar.setMaximumSize(null);
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        atualizar.setText("Atualizar");
        atualizar.setMaximumSize(null);
        atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarActionPerformed(evt);
            }
        });

        excluir.setText("Excluir");
        excluir.setMaximumSize(null);
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });

        novo.setText("Voltar");
        novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoActionPerformed(evt);
            }
        });

        tabelaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaProduto);

        jLabel7.setText("Confimar Senha :");

        javax.swing.GroupLayout jpProdutoLayout = new javax.swing.GroupLayout(jpProduto);
        jpProduto.setLayout(jpProdutoLayout);
        jpProdutoLayout.setHorizontalGroup(
            jpProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpProdutoLayout.createSequentialGroup()
                .addGroup(jpProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpProdutoLayout.createSequentialGroup()
                        .addComponent(atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpProdutoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(novo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpProdutoLayout.createSequentialGroup()
                                .addGroup(jpProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(37, 37, 37)
                                .addGroup(jpProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Senha)
                                    .addComponent(Usuario)
                                    .addComponent(NomeFuncionario)
                                    .addComponent(cpf)
                                    .addComponent(confimSenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jpProdutoLayout.setVerticalGroup(
            jpProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpProdutoLayout.createSequentialGroup()
                .addGroup(jpProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpProdutoLayout.createSequentialGroup()
                        .addComponent(novo)
                        .addGap(39, 39, 39)
                        .addGroup(jpProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(NomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jpProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(confimSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(85, 85, 85)
                        .addGroup(jpProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(excluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jpProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarActionPerformed
        // TODO add your handling code here:
        try
        {
            String Sql=" update funcionarios set func_usuario=?,func_nome=?,func_senha=? where func_cpf=?";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/acai","root","Pro@1974");  
            pst = con.prepareStatement(Sql);
            pst.setString(4,cpf.getText());
            pst.setString(1,Usuario.getText());
            pst.setString(2,NomeFuncionario.getText());
            pst.setString(3,Senha.getText());
           int row = tabelaProduto.getSelectedRow();
            if(tabelaProduto.getModel().getValueAt(row, 2).toString().equals("admin"))
        {
            JOptionPane.showMessageDialog(rootPane, "Este usuario nao pode ser alterado","Excluir", HEIGHT);   
        }else{
           if(Senha.getText() == null ? confimSenha.getText() == null : Senha.getText().equals(confimSenha.getText()))
            {
            pst.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Atualizaçao Realizada com Sucesso!","update", HEIGHT);
            } else
            {
            JOptionPane.showMessageDialog(rootPane, "As Senhas nao coincidem","update", HEIGHT);
            }
            }
        
        }catch (HeadlessException ex){ 
    JOptionPane.showMessageDialog(rootPane, ex,"Erro", HEIGHT);
    }   catch (SQLException ex) {   
        JOptionPane.showMessageDialog(rootPane, ex,"Erro", HEIGHT);
        }   
       showTableData(); 
       limpatxt();
    }//GEN-LAST:event_atualizarActionPerformed

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        // TODO add your handling code here:
        try
        {
            String Sql=" insert into funcionarios values (?,?,?,?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/acai","root","Pro@1974");  
            pst = con.prepareStatement(Sql);
            pst.setString(1,cpf.getText());
            pst.setString(2,Usuario.getText());
            pst.setString(3,NomeFuncionario.getText());
            pst.setString(4,Senha.getText());
            if(Senha.getText() == null ? confimSenha.getText() == null : Senha.getText().equals(confimSenha.getText()))
            {
            pst.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Cadastro Realizado com Sucesso!","Cadastro", HEIGHT);
            } else
            {
            JOptionPane.showMessageDialog(rootPane, "As Senhas nao coincidem","Cadastro", HEIGHT);
            }
        
        }catch (HeadlessException ex){ 
    JOptionPane.showMessageDialog(rootPane, ex,"Erro", HEIGHT);
    }   catch (SQLException ex) {   
        JOptionPane.showMessageDialog(rootPane, ex,"Erro", HEIGHT);
        }   
        showTableData();
        limpatxt();
    }//GEN-LAST:event_cadastrarActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        // TODO add your handling code here:
        try
        {
            String Sql=" delete from funcionarios  where func_cpf=?";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/acai","root","Pro@1974");  
            pst = con.prepareStatement(Sql);
            pst.setString(1,cpf.getText());
            int row = tabelaProduto.getSelectedRow();
        if(tabelaProduto.getModel().getValueAt(row, 2).toString().equals("admin"))
        {
            JOptionPane.showMessageDialog(rootPane, "Este usuario nao pode ser excluido","Excluir", HEIGHT);   
        }else{
        pst.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Exclusão realizada com Sucesso!","Excluir", HEIGHT);}   
        
        }catch (HeadlessException ex){ 
    JOptionPane.showMessageDialog(rootPane, ex,"Erro", HEIGHT);
    }   catch (SQLException ex) {   
        JOptionPane.showMessageDialog(rootPane, ex,"Erro", HEIGHT);
        }   
        showTableData();
        limpatxt();
    }//GEN-LAST:event_excluirActionPerformed

    private void tabelaProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProdutoMouseClicked
        // TODO add your handling code here:
        // get data of the first shell of a JTable row
        int row = tabelaProduto.getSelectedRow();
        cpf.setText(tabelaProduto.getModel().getValueAt(row, 0).toString());
        Usuario.setText(tabelaProduto.getModel().getValueAt(row, 2).toString());
        NomeFuncionario.setText(tabelaProduto.getModel().getValueAt(row, 1).toString());
         Senha.setText(tabelaProduto.getModel().getValueAt(row, 3).toString());
        
        
    }//GEN-LAST:event_tabelaProdutoMouseClicked

    private void novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoActionPerformed
        // TODO add your handling code here:
        action ps = new action();
        this.setVisible(false);
        ps.setVisible(true);
    }//GEN-LAST:event_novoActionPerformed

    public void showTableData()
    {
     try
        {
            String Sql;
         Sql = " select * from funcionarios";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/acai","root","Pro@1974");  
            pst = con.prepareStatement(Sql);
            rs = pst.executeQuery();
            tabelaProduto.setModel(DbUtils.resultSetToTableModel(rs));
        }
    catch (HeadlessException ex){ 
    JOptionPane.showMessageDialog(rootPane, ex,"Erro", HEIGHT);
    }   catch (SQLException ex) {   
        JOptionPane.showMessageDialog(rootPane, ex,"Erro", HEIGHT);
        }   
    }
    public void showtableuser()
    {
    try
        {
            String Sql=" select * from funcionarios";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/acai","root","Pro@1974");  
            pst = con.prepareStatement(Sql);
            rs = pst.executeQuery();
            tabelaProduto.setModel(DbUtils.resultSetToTableModel(rs));
        }
    catch (HeadlessException ex){ 
    JOptionPane.showMessageDialog(rootPane, ex,"Erro", HEIGHT);
    }   catch (SQLException ex) {   
        JOptionPane.showMessageDialog(rootPane, ex,"Erro", HEIGHT);
        }   
    
    }
    public void limpatxt(){
    cpf.setText("");
    NomeFuncionario.setText("");
    Usuario.setText("");
    Senha.setText("");
    confimSenha.setText("");
    
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdmUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdmUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdmUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdmUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AdmUser().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JTextField NomeFuncionario;
    javax.swing.JTextField Senha;
    javax.swing.JTextField Usuario;
    javax.swing.JButton atualizar;
    javax.swing.JButton cadastrar;
    javax.swing.JTextField confimSenha;
    javax.swing.JTextField cpf;
    javax.swing.JButton excluir;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabel4;
    javax.swing.JLabel jLabel7;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JPanel jpProduto;
    javax.swing.JButton novo;
    javax.swing.JTable tabelaProduto;
    // End of variables declaration//GEN-END:variables
}
